### PR TITLE
Merge boosted

### PR DESCRIPTION
**Pull request by scooperstein**

### CODE REVIEW

**Comment by leonardogiannini** [comment]
Everything seems correct except for some random lines here https://github.com/scooperstein/vhbb-nano/pull/1/commits/08f73b3ff9eb6e47df608c064f0f06f7021886dc 

the producer is ok

**Comment by scooperstein** [comment]
thanks @leonardogiannini can you make sure postproc.py and postproc_local.py are okay? postproc_2017_local.py is anyway not used anymore, the idea is that from now on you can just do python postproc.py [isMC] [2016/2017]

**Comment by leonardogiannini** [comment]
yes, I don't see a definition of vhbb2016 and vhbb2017 but the important line https://github.com/scooperstein/vhbb-nano/pull/1/commits/0b47a8bc70b6e797c8eb5ef15d225788bfecac29#diff-403160d82f5e441909647be141fb77f4R53 is correct.

**Comment by scooperstein** [comment]
thanks @leonardogiannini , for the record those modules are defined here https://github.com/scooperstein/vhbb-nano/commit/0b47a8bc70b6e797c8eb5ef15d225788bfecac29#diff-7117ff29809d530991d6318490761199L224

**Comment by scooperstein** [comment]
I'm assuming then that other than the modifications @arizzi is working on to put in the nominal 2017 JEC that will need to be merged that this is good to go for the V2 production. I will organize it better next week but for the V2 it should be fine, all the relevant code is there. Of course if you notice any other issues please let me know.

**Pull request merged**
